# Generated by go2rpm 1.6.0
%bcond_without check

# https://github.com/awslabs/amazon-ecr-credential-helper
%global goipath         github.com/awslabs/amazon-ecr-credential-helper
%global commit          8b0f652990642817f11cd1dffb06d50a735ea251
Version:                0.6.0

%gometa

%global common_description %{expand:
Automatically gets credentials for Amazon ECR on docker push/docker pull.}

%global golicenses      THIRD-PARTY-LICENSES NOTICE LICENSE
%global godocs          docs CODE_OF_CONDUCT.md CONTRIBUTING.md CHANGELOG.md\\\
                        README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Automatically gets credentials for Amazon ECR on docker push/docker pull

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%build
for cmd in ecr-login/cli/docker-credential-ecr-login; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license THIRD-PARTY-LICENSES NOTICE LICENSE
%doc docs CODE_OF_CONDUCT.md CONTRIBUTING.md CHANGELOG.md README.md
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog
