# Generated by go2rpm 1.6.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/inancgumus/screen
%global goipath         github.com/inancgumus/screen
%global commit          06e984b86ed3f2e6e49eb36bf8c49115ccd32b79

%gometa

%global common_description %{expand:
Little helper for clearing the screen using pure Go in a cross-platform way.}

%global golicenses      LICENSE
%global godocs          example README.md

Name:           %{goname}
Version:        0
Release:        %autorelease -p
Summary:        Little helper for clearing the screen using pure Go in a cross-platform way

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
