# Generated by go2rpm 1.6.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/azazeal/pause
%global goipath         github.com/azazeal/pause
Version:                1.1.0

%gometa

%global common_description %{expand:
Pause implements a way to suspend execution until a Context is either done or a
timeout has been reached.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Pause implements a way to suspend execution until a Context is either done or a timeout has been reached

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
