# Generated by go2rpm 1.6.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/buildpacks/imgutil
%global goipath         github.com/buildpacks/imgutil
%global commit          7a271a852e31e13110ac2cdb77db211721332c52

%gometa

%global common_description %{expand:
Helpful utilities for working with images.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Version:        0
Release:        %autorelease -p
Summary:        Helpful utilities for working with images

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/sclevine/spec)

%description
%{common_description}

%gopkg

%prep
%goprep
rm -rf tools/bcdhive_generator

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
# require Docker
%gocheck -d fakes -d local -d remote
%endif

%gopkgfiles

%changelog
%autochangelog
