# Generated by go2rpm 1.6.0
%bcond_without check

# https://github.com/buildpacks/lifecycle
%global goipath         github.com/buildpacks/lifecycle
Version:                0.14.1

%gometa

%global common_description %{expand:
Reference implementation of the Cloud Native Buildpacks lifecycle.}

%global golicenses      LICENSE
%global godocs          RELEASE.md CONTRIBUTING.md DEVELOPMENT.md README.md\\\
                        IMAGE.md

Name:           %{goname}
Release:        %autorelease
Summary:        Reference implementation of the Cloud Native Buildpacks lifecycle

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc RELEASE.md CONTRIBUTING.md DEVELOPMENT.md README.md IMAGE.md
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog
