# Generated by go2rpm 1.6.0
%bcond_without check

# https://github.com/superfly/flyctl
%global goipath         github.com/superfly/flyctl
Version:                0.0.333

%gometa

%global common_description %{expand:
Command line tools for fly.io services.}

%global golicenses      LICENSE deps/wintun/LICENSE.txt
%global godocs          doc example building.md README.md\\\
                        scripts/changelog.sh helpgen/README.md\\\
                        deps/wintun/README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Command line tools for fly.io services

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done
%gobuild -o %{gobuilddir}/bin/flyctl %{goipath}
for cmd in helpgen doc; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE deps/wintun/LICENSE.txt
%doc doc example building.md README.md scripts/changelog.sh helpgen/README.md
%doc deps/wintun/README.md
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog
