# Generated by go2rpm 1.6.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/aybabtme/iocontrol
%global goipath         github.com/aybabtme/iocontrol
%global commit          ad15bcfc95a08d0b9d072012fb7618512aafb99b

%gometa

%global common_description %{expand:
Measure and throttle the rate at which data is transferred.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Version:        0
Release:        %autorelease -p
Summary:        Measure and throttle the rate at which data is transferred

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
